[tool.ruff]
fix = true
include = ["*.py", "*.pyi", "**/pyproject.toml", "*.ipynb"]
select = [
"ARG", # flake8-unused-arguments
"B", # flake8-bugbear
"C4", #flake8-comprehensions
"COM", #flake8-commas
"D", # pydocstyle
"E", # pycodestyle
"EM", # flake8-errmsg
"F", # pyflakes
"I", # isort
"N", # pep8-naming
"PT", #flake8-pytest-style
"PTH", # flake8-use-pathlib
"Q", # flake8-quotes
"UP", # pyupgrade
]
target-version = "py311"
line-length = 100
ignore-init-module-imports = true

[tool.ruff.per-file-ignores]
"__init__.py" = ["E402"]
"docs/**" = ["D"]
"tests/**" = ["D"]
"notebooks/**" = ["D"]

[tool.ruff.pydocstyle]
convention = "google"

[tool.ruff.isort]
force-single-line = true
force-sort-within-sections = true
lines-after-imports = 1
known-local-folder = ["src"]
